analogdevicesinc/EVAL-ADICUP3029

.gitignore

This commit will ensure that no files from Debug and Release folder will be
uploaded to github. We will use this for all ADICUP projects and will
ensure consistency across platforms. This folders will be automatically
generated once the user builds his project.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>

.gitignore: Update with Debug and Release folders

---

.travis.yml
ci/scripts/astyle.sh
ci/scripts/astyle_config
ci/scripts/cppcheck.sh
ci/travis/before_install_darwin
ci/travis/before_install_linux

Add Travis to EVAL-ADICUP3029 repo.
The purpose of it is to perform static analysis with the cppcheck tool
on all source files and check if code style of the files modified/
added per commit correspond to the standards.

General: add Travis

---

projects/ADuCM3029_demo_cli/.cproject
projects/ADuCM3029_demo_cli/.project
projects/ADuCM3029_demo_cli/Debug/RTE/Device/ADuCM3029/subdir.mk
projects/ADuCM3029_demo_cli/Debug/makefile
projects/ADuCM3029_demo_cli/Debug/src/subdir.mk
projects/ADuCM3029_demo_cli/Debug/system/pinmux/GeneratedSources/subdir.mk
projects/ADuCM3029_demo_cli/Debug/system/subdir.mk

The compiler path to the "include" folder was a literal path to the
folder three on my specific machine and not a variable path to the
workspace folder. As such, the project could not be compiled on other
machines. Update the compiler path to the "include" folder to resolve
this issue.

cli_demo: fix compiler path to "include" folder

---

cmsis-packs/releases/ble/AnalogDevices.ADI-BleSoftware.pdsc
cmsis-packs/releases/wifi/AnalogDevices.ADI-WifiSoftware.pdsc

The url must point to the raw repository link not the master. This patch
fixes that issue.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>

cmsis-packs: release: Fix pdsc urls

---

projects/ADuCM3029_demo_cn0435/Scripts/Basic MODBUS Examples/read_adc_analog_input_registers.py
projects/ADuCM3029_demo_cn0435/Scripts/Basic MODBUS Examples/read_common_analog_input_registers.py
projects/ADuCM3029_demo_cn0435/Scripts/Basic MODBUS Examples/set_adc_output_code.py
projects/ADuCM3029_demo_cn0435/Scripts/Basic MODBUS Examples/set_dac_output_voltage.py
projects/ADuCM3029_demo_cn0435/Scripts/dcs_cn0414_utilities.py
projects/ADuCM3029_demo_cn0435/Scripts/dcs_cn0418_utilities.py
projects/ADuCM3029_demo_cn0435/Scripts/dcs_cn0435.py
projects/ADuCM3029_demo_cn0435/Scripts/dcs_cn0435_utilities.py
projects/ADuCM3029_demo_cn0435/Scripts/detect_configuration.py
projects/ADuCM3029_demo_cn0435/Scripts/read_write_modbus_registers.py

Add python scripts for CN-0435 project.
- Add basic python scripts to read or write MODBUS registers from CN-0414 and/or CN-0418 boards.
- Add main scripts to interact via MODBUS commands with one or more CN-0414 or CN-0418 boards which compose a DCS or a PLC system.

Cn 0435 scripts

---

projects/ADuCM3029_demo_cn0435/.cproject
projects/ADuCM3029_demo_cn0435/.project
projects/ADuCM3029_demo_cn0435/src/platform_drivers.c

This patch fixes compile errors that snuck in:
- add the 'error' label for the 'gpio_get()' method in 'platform_drivers' module;
- fix project compile paths that search for the development name instead of the actual name of the project.

CN0435 build fix.

---

projects/ADuCM3029_demo_esp8266/src/ESP8266.c

Travis static analysis reported out of bounds errors for literal strings
on the changed "strncat" functions. Fix errors.

demo_esp8266: fix out of bounds errors

---

projects/ADuCM3029_demo_ad5592r_ad5593r/src/aio_dio_pdmz.c

Reading the ADC in test mode returns 16 bits, but only the first 12 are
useful data. The application was considering all the 16 bits and the test
mode never returned positive result because of it. Mask the most
significant 4 bits of the ADC return value to fix the issue.

AD5592/3R_PMOD: Fix test mode ADC reading

---

projects/ADuCM3029_demo_ad5592r_ad5593r/src/aio_dio_pdmz.c
projects/ADuCM3029_demo_ad5592r_ad5593r/src/aio_dio_pdmz.h

This patch adds a ADC streaming option that reads the ADC input
continuously from all channels. If the channel is not setup as ADC it shows
an appropriate message.
Signed-off-by: Drimbarean <Andrei.Drimbarean@analog.com>

AD5592/3r_demo: add streaming command to project

---

projects/ADuCM3029_demo_cn0401/src/can_obj_layer.c

Cast object layer data pointer to (uint8_t *) before incrementing it
past the message header to ensure correct incrementation (12 and 8
bytes, respectively, instead of 48 and 32).

cn0401_demo: fix receive function bug

---

projects/ADuCM3029_demo_cn0503/scripts/get_data.py

-s value is printed as integer so its type must be int too.
Signed-off-by: Mihail Chindris <mihail.chindris@analog.com>

projects:cn0503:scripts: fix -s error

---

projects/ADuCM3029_demo_ad7124_8PMDZ/src/cli.c

When large streams of data were read from the device UART read buffer sometimes
dropped. If the buffer is dropped, add another.

projects:ad7124_8pmdz: fix CLI buffer drop

---

projects/ADuCM3029_demo_cn0401/src/cn0401.c

Perform unconditional jump instead of direct return.

cn0401: fix memory leak

---

build_projects.yml

The default branch is master so artifacts should be published on new
master commits
Signed-off-by: Mihail Chindris <mihail.chindris@analog.com>

build_projects.yml: Publish artifacts when in master branch

---

projects/ADuCM3029_demo_cn0536/app_src/geiger_counter.h

5 was used only for faster debugging. 10 seconds is the correct
value.
Signed-off-by: Mihail Chindris <mihail.chindris@analog.com>

projects:ADuCM3029_demo_cn0536: Set SAMPLING_PERIOD to 10

---

projects/ADuCM3029_demo_cn0548/scripts/CN0548_simple_plot.py

User types now the entire Serial line string required.
E.g. "COM7", "/dev/ttyUSB0"

projects:cn0548: update Serial input

---

projects/ADuCM3029_demo_cn0503/src/adpd410x.c
projects/ADuCM3029_demo_cn0503/src/adpd410x.h
projects/ADuCM3029_demo_cn0503/src/cn0503.c
projects/ADuCM3029_demo_cn0503/src/cn0503.h
projects/ADuCM3029_demo_cn0503/src/platform_source/flash.c
projects/ADuCM3029_demo_cn0503/src/platform_source/irq.c

Add support for four fluorescence-decay-related commands in the CN0503 firmware (in which, the decay of a fluorophore is measured over a period of time after an initial LED pulse.) See commit [249690f](https://github.com/analogdevicesinc/EVAL-ADICUP3029/commit/249690fda19f024deef3264191273237089468e7) for a lengthy description of the command functionality, as well as helper functions implemented from each command.
In gpio.c, add a function to register an interrupt handler to a GPIO pin. This allows the fluorescence decay measurements to use an interrupt-based FIFO sampling method.
In flash.c, fix a few bugs regarding the use of the flash address (as far as I can tell, the flash address was used to represent a byte index in some places, and a word index in others).

CN0503 Platform Fluorescence Decay Support

---

projects/ADuCM3029_demo_cn0503/.cproject
projects/ADuCM3029_demo_cn0503/src/adpd410x.c
projects/ADuCM3029_demo_cn0503/src/adpd410x.h
projects/ADuCM3029_demo_cn0503/src/app_config.h
projects/ADuCM3029_demo_cn0503/src/cn0503.c
projects/ADuCM3029_demo_cn0503/system.svc
projects/ADuCM3029_demo_cn0503/system/pinmux/GeneratedSources/pinmux_config.c

Add support for the ADPD4100 device which works using the SPI protocol.
Current version offers support only for I2C communication. 

cn0503: add ADPD4100 support

---

projects/ADuCM3029_demo_cn0567/Makefile
projects/ADuCM3029_demo_cn0567/README.md
projects/ADuCM3029_demo_cn0567/builds.json
projects/ADuCM3029_demo_cn0567/pinmux_config.c
projects/ADuCM3029_demo_cn0567/src.mk
projects/ADuCM3029_demo_cn0567/src/ADuCM3029_demo_cn0567.c
projects/ADuCM3029_demo_cn0567/src/app_config.h
projects/ADuCM3029_demo_cn0567/src/cn0567.c
projects/ADuCM3029_demo_cn0567/src/cn0567.h
projects/ADuCM3029_demo_cn0567/src/cn0567_config.h
projects/ADuCM3029_demo_cn0567/src/parameters.h

Initial version of the CN0567 project.
Provides IIO support for both versions of the reference design:
ADPD4100 and ADPD4101.
A part of the requirement is to have the device configuration separate
from the application implementation for easier usage by the customers
(timeslot configuration / register configuration). This is done via
`cn0567_config.h` file.
(The project is a compact/reworked version of CN0503 project)

cn0567: initial implementation

---

projects/ADuCM3029_demo_cn0536/app_src/communication.c

Replace bool with int32_t. If FAILURE (-1) is returned
for a bool value it will be 1. Then a check with ret < 0
will fail.
Signed-off-by: Mihail Chindris <mihail.chindris@analog.com>

projects:ADuCM3029_demo_cn0536: Fix init_mqtt ret

---

projects/ADuCM3029_demo_cn0567/src/cn0567_config.h

Reduce the output current such that it matches the hardware
specifications of the optocouplers.

projects: cn0567: reduce led current

---

projects/ADuCM3029_demo_cn0567/src/ADuCM3029_demo_cn0567.c

Add buffer support for the IIO application of the cn0567 board.

cn0567: add IIO buffer support

---

projects/ADuCM3029_demo_cn0567/builds.json
projects/ADuCM3029_demo_cn0567/src/app_config.h
projects/ADuCM3029_demo_cn0567/src/cn0567.c
projects/ADuCM3029_demo_cn0567/src/cn0567_config.h

Add support for multiple timeslot configurations, one default and one
for the waterquality demo.
Update *.json file to create separate hex files for each configuration.

cn0567:add support for multiple configs

---

projects/ADuCM3029_demo_cn0548/builds.json
projects/ADuCM3029_demo_cn0548/src/app_config.h

Add application configuration such that both bipolar and unipolar
configuration of the ADC are available in the application layer and
build process.

cn0548: add support for bipolar/unipolar config

---

azure-pipelines.yml

As the variable name states, the target branch should contain information about the branch against which the new commits / pull request are redirected. Currently the variable contains the name of the branch on which the commits are made (source branch). Update the variable value accordingly.

azure-pipelines: fix target branch

---

ci/release_project.sh

This script is used in the release pipeline in order to add the tag of the release on the last commit.

Add script for release job

---

ci/lib.sh

The no-OS master branch is now renamed to main.
Update the script link accordingly.

ci: lib: switch to main branch
